import type { Metadata } from "next";
import type { ComponentType, SVGProps } from "react";
import { PageHero } from "@/components/ui/PageHero";
import { SectionHeading } from "@/components/ui/SectionHeading";
import { ButtonLink } from "@/components/ui/Button";
import { Badge, ValueCard } from "@/components/ui/Misc";
import {
  ArrowRightIcon,
  BackpackIcon,
  CalendarCheckIcon,
  ChartIcon,
  CheckIcon,
  QrCodeIcon,
  RouteIcon,
  ScanIcon,
  SmartphoneIcon,
} from "@/components/ui/Icons";
import { ScanFlow } from "@/components/sections/ScanFlow";
import { PartnerApplicationForm } from "@/components/sections/PartnerApplicationForm";
import {
  foundingProgram,
  partnerFlow,
  receptionDeskSteps,
  whyJoin,
  type FlowStep,
} from "@/data/partners";
import { vibes } from "@/data/vibes";

export const metadata: Metadata = {
  title: "Become a Partner",
  description:
    "Join NEXT STOP and become part of a growing network of backpacker hostels. One QR code at reception, a digital NEXT PASS on the guest's phone, and onward bookings attributed back to you.",
};

/** One icon per step of `partnerFlow`, in order. */
const flowIcons: ComponentType<SVGProps<SVGSVGElement>>[] = [
  BackpackIcon,
  QrCodeIcon,
  ScanIcon,
  SmartphoneIcon,
  CalendarCheckIcon,
  ChartIcon,
];

/** Who does each part. The pills exist to show how little lands on the desk. */
const actorLabels: Record<FlowStep["actor"], string> = {
  hostel: "Your desk",
  traveller: "The guest",
  network: "NEXT STOP",
};

/**
 * `receptionDeskSteps` is ordered: point at the code, the guest scans, done.
 * Only the first one is work for the hostel — the labels make that explicit.
 */
const deskOwnership = [
  { label: "Your part", isHostel: true },
  { label: "The guest's phone", isHostel: false },
  { label: "Nothing comes back", isHostel: false },
];

const noAdminPoints = [
  {
    title: "It happens on their phone",
    description:
      "The guest scans with their own camera and the pass is generated there. Your desk is not involved after the sentence.",
  },
  {
    title: "Nothing to print per guest",
    description:
      "One code on the desk serves everyone who walks in, for as long as you are a partner.",
  },
  {
    title: "Nothing to operate",
    description:
      "Your staff never log in and never create a code by hand. The pass is generated by NEXT STOP.",
  },
];

export default function PartnersPage() {
  return (
    <>
      <PageHero
        size="lg"
        eyebrow="For hostels"
        // U+2028 is a forced line break in CSS text layout, which keeps the
        // three-line heading intact without changing the shared PageHero.
        title="Thousands of hostels. Millions of backpackers. Let's"
        accent="connect them!"
        image={vibes.rooftopFriends.src}
        imageAlt={vibes.rooftopFriends.alt}
        subtitle="Join NEXT STOP and become part of a rapidly growing network of backpacker hostels."
        crumbs={[{ label: "Home", href: "/" }, { label: "Become a Partner" }]}
      >
        <div className="flex flex-wrap gap-3">
          <ButtonLink href="#apply" variant="primary" size="lg">
            Become a Founding Partner
            <ArrowRightIcon className="h-3.5 w-3.5 transition-transform duration-200 group-hover:translate-x-0.5" />
          </ButtonLink>
          <ButtonLink href="/partners/benefits" variant="light" size="lg">
            See partner benefits
          </ButtonLink>
        </div>
      </PageHero>

      {/* How it works for hostels */}
      <section
        aria-labelledby="for-hostels"
        className="container-page pt-12 lg:pt-14"
      >
        <SectionHeading
          id="for-hostels"
          title="How NEXT STOP works"
          accent="for hostels"
          subtitle="One QR code at reception. No channel manager, no new software, no change to how you run check-in."
        />

        <div className="grid gap-8 lg:grid-cols-[1.6fr_1fr] lg:gap-14">
          <div>
            <p className="max-w-[68ch] text-[14.5px] leading-[1.75] text-ink-600">
              Most backpackers do not plan a whole trip before they leave. They
              decide the next city while they are standing in the one before it,
              usually on the advice of whoever is behind the desk. NEXT STOP
              turns that conversation into something both hostels benefit from:
              you display one QR code, the guest scans it with their own phone,
              and the digital NEXT PASS that appears carries your hostel&apos;s
              identifier onward.
            </p>
            <p className="mt-4 max-w-[68ch] text-[14.5px] leading-[1.75] text-ink-600">
              Nothing is added to your working day except pointing at that code.
              There is no inventory to sync, no rates to mirror across channels,
              nothing to print for each guest and no dashboard anyone has to
              keep open during a busy shift. NEXT STOP handles the reservation
              using the information you already list on other major booking
              platforms, and your only job is to send guests onward through the
              network.
            </p>
          </div>

          <aside className="rounded-xl border border-ink-100 bg-white p-5 shadow-[0_2px_10px_-6px_rgba(6,9,15,0.14)]">
            <h3 className="text-[14px] font-semibold text-ink-900">
              What joining actually involves
            </h3>
            <ul className="mt-4 space-y-3">
              {[
                "A listing page for your hostel, written with you rather than scraped.",
                "Your own NEXT STOP QR code, on a tabletop sign and a wall poster.",
                "One sentence added to check-in, and nothing removed from it.",
                "Start making additional profit by sending backpackers through within our network.",
                "Commercial terms agreed with you directly during launch. You won\u2019t pay anything, you just benefit!",
              ].map((item) => (
                <li key={item} className="flex gap-2.5">
                  <CheckIcon
                    aria-hidden
                    className="mt-0.5 h-4 w-4 shrink-0 text-brand-500"
                  />
                  <span className="text-[12.5px] leading-relaxed text-ink-600">
                    {item}
                  </span>
                </li>
              ))}
            </ul>
          </aside>
        </div>

        <ul className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
          {whyJoin.map((item) => (
            <li key={item.title}>
              <ValueCard
                icon={item.icon}
                title={item.title}
                description={item.description}
              />
            </li>
          ))}
        </ul>
      </section>

      {/* The partner journey */}
      <section
        aria-labelledby="partner-journey"
        className="container-page pt-12 lg:pt-14"
      >
        <SectionHeading
          id="partner-journey"
          title="The partner"
          accent="journey"
          subtitle={`${partnerFlow.length} steps from check-in to attribution.`}
        />

        <ol className="mt-8 grid gap-8 lg:grid-cols-3 lg:gap-x-4 lg:gap-y-12">
          {partnerFlow.map((item, index) => {
            const Icon = flowIcons[index] ?? RouteIcon;
            const isLast = index === partnerFlow.length - 1;
            const endsDesktopRow = (index + 1) % 3 === 0;
            const isHostel = item.actor === "hostel";

            return (
              <li
                key={item.step}
                className="relative flex gap-4 lg:flex-col lg:items-center lg:gap-0 lg:text-center"
              >
                {/* Connector — vertical on mobile, horizontal on desktop */}
                {!isLast ? (
                  <span
                    aria-hidden
                    className="absolute top-14 left-[27px] h-[calc(100%+2rem-3.5rem)] border-l-2 border-dashed border-brand-200 lg:hidden"
                  />
                ) : null}
                {!endsDesktopRow ? (
                  <span
                    aria-hidden
                    className="absolute top-7 right-[calc(-50%+2.25rem)] left-[calc(50%+2.25rem)] hidden border-t-2 border-dashed border-brand-200 lg:block"
                  />
                ) : null}

                <div className="relative shrink-0">
                  <span
                    aria-hidden
                    className="absolute -top-1 -left-1.5 z-10 grid h-5 w-5 place-items-center rounded-full bg-brand-500 text-[10.5px] font-bold text-white"
                  >
                    {item.step}
                  </span>
                  <span
                    aria-hidden
                    className={`grid h-14 w-14 place-items-center rounded-full ${
                      isHostel
                        ? "bg-brand-500 text-white ring-4 ring-brand-100"
                        : "bg-brand-50 text-ink-900"
                    }`}
                  >
                    <Icon className="h-6 w-6" />
                  </span>
                </div>

                <div className="lg:mt-4">
                  <p className="mb-2">
                    <Badge tone={isHostel ? "brand" : "muted"}>
                      {actorLabels[item.actor]}
                    </Badge>
                  </p>
                  <h3 className="text-[15px] font-semibold text-ink-900">
                    <span className="sr-only">Step {item.step}: </span>
                    {item.title}
                  </h3>
                  <p className="mt-1.5 max-w-[38ch] text-[12.5px] leading-relaxed text-ink-500 lg:mx-auto">
                    {item.description}
                  </p>
                </div>
              </li>
            );
          })}
        </ol>

        {/* Reception flow — the whole pitch in one panel */}
        <div className="mt-12 rounded-2xl border border-brand-200 bg-brand-50 p-6 sm:p-8">
          <Badge tone="brand">
            <ScanIcon aria-hidden className="h-3 w-3" />
            Reception flow
          </Badge>

          <p className="mt-5 flex flex-wrap items-baseline gap-x-3 gap-y-1 text-[22px] leading-tight font-bold sm:text-[27px]">
            <span className="text-ink-900">One QR.</span>
            <span className="text-brand-600">A few seconds.</span>
            <span className="text-ink-900">Another happy backpacker.</span>
          </p>

          <p className="mt-4 max-w-[66ch] text-[13.5px] leading-relaxed text-ink-600">
            Three things happen at the desk, and only the first one is yours.
            The rest is the guest&apos;s phone and our side of the network — so
            the flow does not get slower when reception is busy.
          </p>

          <ol className="mt-7 grid gap-4 sm:grid-cols-3">
            {receptionDeskSteps.map((step, index) => {
              const ownership = deskOwnership[index];
              const isHostel = ownership?.isHostel ?? false;

              return (
                <li
                  key={step.title}
                  className={`flex gap-3 rounded-xl border bg-white p-4 sm:flex-col sm:gap-0 ${
                    isHostel
                      ? "border-brand-500 shadow-[0_2px_14px_-6px_rgba(234,42,107,0.45)]"
                      : "border-brand-100"
                  }`}
                >
                  <span
                    aria-hidden
                    className={`grid h-7 w-7 shrink-0 place-items-center rounded-full text-[11px] font-bold sm:mb-3 ${
                      isHostel
                        ? "bg-brand-500 text-white"
                        : "bg-ink-100 text-ink-600"
                    }`}
                  >
                    {index + 1}
                  </span>
                  <div>
                    <p className="text-[13.5px] font-semibold text-ink-900">
                      {step.title}
                    </p>
                    <p className="mt-1 text-[12px] leading-relaxed text-ink-500">
                      {step.description}
                    </p>
                    {ownership ? (
                      <p className="mt-3">
                        <Badge tone={isHostel ? "brand" : "muted"}>
                          {ownership.label}
                        </Badge>
                      </p>
                    ) : null}
                  </div>
                </li>
              );
            })}
          </ol>

        </div>
      </section>

      {/* What it looks like at reception */}
      <section
        aria-labelledby="at-reception"
        className="container-page pt-12 lg:pt-14"
      >
        <SectionHeading
          id="at-reception"
          title="What it looks like"
          accent="at reception"
          subtitle="A code on your desk, a pass on their phone."
        />

        <p className="mb-7 max-w-[68ch] text-[14.5px] leading-[1.75] text-ink-600">
          The NEXT PASS is a digital pass on the guest&apos;s phone. Every
          guest scans the same QR code at reception. This opens a NEXT STOP page
          in their browser and creates a pass linked to your hostel.
        </p>

        <ScanFlow />

        <ul className="mt-6 grid gap-5 sm:grid-cols-3">
          {noAdminPoints.map((point) => (
            <li
              key={point.title}
              className="rounded-xl border border-ink-100 bg-white p-5 shadow-[0_2px_10px_-6px_rgba(6,9,15,0.14)]"
            >
              <h3 className="flex items-center gap-2 text-[15px] font-semibold text-ink-900">
                <CheckIcon aria-hidden className="h-4 w-4 text-brand-500" />
                {point.title}
              </h3>
              <p className="mt-1.5 text-[12.5px] leading-relaxed text-ink-500">
                {point.description}
              </p>
            </li>
          ))}
        </ul>
      </section>

      {/* Founding Partner Programme */}
      <section
        aria-labelledby="founding-programme"
        className="container-page pt-12 lg:pt-14"
      >
        <SectionHeading
          id="founding-programme"
          title="The Founding Partner"
          accent="Programme"
          subtitle="What the first hostels in the network get, and give, before it scales."
        />

        <div className="rounded-2xl bg-ink-950 p-7 sm:p-9 lg:p-11">
          <Badge tone="open">Now open</Badge>
          <p className="mt-5 max-w-[66ch] text-[14.5px] leading-relaxed text-white/75">
            A founding partner is not a discounted tier — it is a hostel that
            joins while the product is still being decided. That means more
            influence over how the QR flow, the pass and the listing pages work,
            and a direct relationship with the people building them, in exchange
            for the patience an early network asks for.
          </p>

          <ul className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
            {foundingProgram.map((item) => (
              <li key={item.title}>
                <ValueCard
                  tone="dark"
                  icon={item.icon}
                  title={item.title}
                  description={item.description}
                />
              </li>
            ))}
          </ul>

          <div className="mt-8 flex flex-wrap gap-3">
            <ButtonLink href="#apply" variant="primary">
              Apply as a founding partner
              <ArrowRightIcon className="h-3.5 w-3.5 transition-transform duration-200 group-hover:translate-x-0.5" />
            </ButtonLink>
            <ButtonLink href="/partners/resources" variant="light">
              Partner resources
            </ButtonLink>
          </div>
        </div>
      </section>

      {/* Application form */}
      <section
        id="apply"
        aria-labelledby="apply-heading"
        className="container-page scroll-mt-[88px] py-14"
      >
        <SectionHeading
          id="apply-heading"
          title="Apply to become"
          accent="a partner"
          subtitle="Tell us about the hostel. A person reads every application."
        />
        <div className="max-w-[860px]">
          <PartnerApplicationForm />
        </div>
      </section>
    </>
  );
}
