import type { Metadata } from "next";
import Link from "next/link";
import {
  LegalPageLayout,
  type LegalSection,
} from "@/components/sections/LegalPageLayout";

export const metadata: Metadata = {
  title: "Terms & Conditions",
  description:
    "The terms for using NEXT STOP: how the NEXT PASS works, who your booking is actually with, what partner hostels are responsible for, and how cancellations are handled.",
};

const sections: LegalSection[] = [
  {
    id: "using-next-stop",
    heading: "Using NEXT STOP",
    body: (
      <>
        <p>
          NEXT STOP is a network that introduces travellers to independent
          hostels and lets a stay at one partner unlock a direct booking at the
          next. Using this site means accepting the terms on this page. If you
          do not accept them, please do not use the site or a NEXT PASS.
        </p>
        <p>
          You can browse destinations, hostels, routes and guides without an
          account. Where we give information about a city, a journey time or a
          hostel, we take reasonable care to keep it accurate, but travel
          details change and listings are supplied in part by the hostels
          themselves.
        </p>
        <p>
          You agree not to misuse the service: no scraping listings at scale, no
          attempts to break the booking flow, no duplicating or reselling pass
          codes, and no submitting false bookings or applications. We can
          suspend access where that happens.
        </p>
        <p>
          NEXT STOP is currently a pre-launch preview. Booking is not open,
          prices shown are demo figures, the hostels listed are illustrative
          rather than signed partners, and the forms do not transmit anything.
        </p>
      </>
    ),
  },
  {
    id: "next-pass",
    heading: "NEXT PASS",
    body: (
      <>
        <p>
          A NEXT PASS is digital. Every partner hostel displays its own NEXT
          STOP QR code at reception; scanning it with your phone opens a NEXT
          STOP page in your browser, and a short flow generates a unique pass
          code that is shown on your screen. There is no app to install, nothing
          printed, nothing handed over and no membership to manage.
        </p>
        <p>
          The code unlocks the direct rate that partner hostels set for pass
          holders. It does not guarantee availability, a particular price or a
          particular room — it opens the direct booking channel, and what is
          free on your dates is up to the hostel.
        </p>
        <ul>
          <li>Each code is valid for a single unlocked booking.</li>
          <li>
            A pass is intended for the next leg of a trip rather than for
            indefinite use; the validity period is shown on the pass when it is
            generated.
          </li>
          <li>
            Codes are generated to a device rather than to a named account, so a
            pass carries no name and cannot be looked up by one. Save the code
            while you have it, or scan the same QR code again while you are
            still at that hostel.
          </li>
          <li>
            Codes may not be sold, published, bulk-distributed or generated
            automatically, and QR codes may only be displayed by the partner
            they were issued to.
          </li>
          <li>
            A code found to be duplicated, forged, resold or generated by
            automated means can be cancelled.
          </li>
        </ul>
        <p>
          Generating a pass has no purchase step. If any charge ever applies to
          a pass, it will be shown in the flow before you confirm it, with the
          terms that go with it — never added afterwards.
        </p>
      </>
    ),
  },
  {
    id: "bookings",
    heading: "Bookings",
    body: (
      <>
        <p>
          This is the important part: your booking is made directly with the
          partner hostel. NEXT STOP connects the two of you, carries the
          reservation details across and confirms the code — it is not the
          accommodation provider, does not own or operate any hostel, and is not
          a party to your stay.
        </p>
        <p>
          The contract for the stay is between you and the hostel, on that
          hostel&rsquo;s terms. It is the hostel that confirms the booking,
          holds the bed, sets the house rules, handles check-in and deals with
          anything that happens while you are there.
        </p>
        <p>
          A booking request becomes a booking when the hostel confirms it.
          Please check the dates, room type and number of guests on that
          confirmation, because those are the details the hostel will work from.
          If something looks wrong, contact the hostel first — they hold the
          reservation.
        </p>
        <p>
          Hostels set their own minimum age, arrival window and identification
          requirements. Most partners require guests in shared dorms to be 18 or
          over, and you are responsible for arriving with the documents your
          destination requires.
        </p>
      </>
    ),
  },
  {
    id: "partner-hostels",
    heading: "Partner Hostels",
    body: (
      <>
        <p>
          Hostels join the network by recommendation and by agreement with us.
          Each partner is responsible for the accuracy of its own listing —
          description, photographs, amenities, house rules and the direct rate
          it offers to pass holders — and for keeping that listing current.
        </p>
        <p>
          Partners agree to display their own NEXT STOP QR code where guests can
          see it, to honour the direct rate for a valid NEXT PASS code when the
          room is available, and to treat pass holders as ordinary direct guests
          in every other respect. The QR code is issued to that hostel alone and
          may not be copied, shared or displayed elsewhere. In return, a partner
          is credited when a pass generated from its QR code leads to a booking
          elsewhere in the network.
        </p>
        <p>
          We check partners before listing them and act on what guests tell us,
          but we do not run their properties and cannot guarantee the standard
          of any particular stay. A hostel can be removed from the network if it
          stops meeting the standards the network depends on.
        </p>
        <p>
          If you run a hostel and want to join, the{" "}
          <Link href="/partners">partner page</Link> explains what is involved
          and what we need from you.
        </p>
      </>
    ),
  },
  {
    id: "payments",
    heading: "Payments",
    body: (
      <>
        <p>
          Generating a NEXT PASS involves no payment step: you scan the
          hostel&rsquo;s QR code and the code appears on your phone. If a charge
          ever applies to a pass, it will be shown in the flow before you
          confirm it. NEXT STOP does not charge travellers a booking fee, a
          service fee or a commission on top of the room rate.
        </p>
        <p>
          Payment for the stay itself is a matter between you and the hostel,
          following the payment terms shown on your booking. Depending on the
          partner that may mean a deposit taken at the time of booking with the
          balance due on arrival, or the full amount payable at the property.
        </p>
        <p>
          Prices are shown in euro and include the taxes stated at the time of
          booking. Local tourist taxes, city taxes, cleaning charges, key
          deposits and optional extras such as linen, breakfast or luggage
          storage may be collected separately by the hostel and, where they are,
          are identified before you confirm.
        </p>
        <p>
          Where a payment is processed online, it is handled by a regulated
          payment provider. We do not store your card details.
        </p>
      </>
    ),
  },
  {
    id: "cancellations",
    heading: "Cancellations",
    body: (
      <>
        <p>
          Cancellation terms are set by each hostel, not by NEXT STOP. The terms
          that apply to your booking are the ones shown with that booking and
          repeated in your confirmation, so it is worth reading them before you
          confirm — free cancellation windows vary between partners, and some
          rates are non-refundable.
        </p>
        <p>
          To cancel or change a booking, deal with the hostel directly, in
          writing where possible, and keep the confirmation. Refunds, where they
          are due, are issued by the hostel under its own terms and by the
          method used to pay.
        </p>
        <p>
          Cancelling a booking does not consume your relationship with the
          network: where a hostel cancels a booking that a valid code unlocked,
          we will help you use the network to find another partner in the same
          city, and the code is released so it can unlock that booking instead.
        </p>
        <p>
          Not turning up without cancelling is treated as a no-show under the
          hostel&rsquo;s terms, which usually means the booking is lost and any
          deposit is kept.
        </p>
      </>
    ),
  },
  {
    id: "user-responsibilities",
    heading: "User Responsibilities",
    body: (
      <>
        <p>When you use NEXT STOP or stay with a partner, you agree to:</p>
        <ul>
          <li>
            give accurate booking details, and use your own name and contact
            details;
          </li>
          <li>
            be old enough to make the booking, and to meet the partner&rsquo;s
            age and identification requirements on arrival;
          </li>
          <li>
            respect the house rules of the hostel you are staying in — quiet
            hours, shared kitchens, lockers, guests and everything else;
          </li>
          <li>
            treat the property and other guests decently; hostels can refuse or
            end a stay where that does not happen;
          </li>
          <li>
            arrange your own travel insurance, visas and documentation for the
            countries you are travelling through;
          </li>
          <li>
            use pass codes as intended — one booking per code, no reselling, no
            automated use.
          </li>
        </ul>
        <p>
          Anything you send us through a form must be yours to send, and must
          not be unlawful or deliberately misleading. Reviews and feedback
          should describe your own experience.
        </p>
      </>
    ),
  },
  {
    id: "limitation-of-liability",
    heading: "Limitation of Liability",
    body: (
      <>
        <p>
          Because the stay is a contract between you and the hostel, NEXT STOP
          is not liable for the hostel&rsquo;s performance of it: the condition
          of the property, the standard of service, overbooking, lost or damaged
          belongings, injury, or anything that happens during your stay. Claims
          of that kind are made against the hostel.
        </p>
        <p>
          We work to keep listings, prices and travel information accurate, but
          we do not warrant that everything on the site is complete or
          error-free, or that the site is always available and free of
          interruption. We are not responsible for delays or failures caused by
          events outside our reasonable control, including transport
          disruptions, strikes, extreme weather and network outages.
        </p>
        <p>
          To the extent the law allows, our liability in connection with the
          service is limited to any amount you have actually paid to NEXT STOP
          in connection with it — and generating a pass involves no payment to
          us, so for most travellers that amount is nothing at all. Nothing in
          these terms limits
          liability for death or personal injury caused by negligence, for
          fraud, or for any other liability that cannot lawfully be excluded —
          and none of this affects the statutory consumer rights you have where
          you live.
        </p>
      </>
    ),
  },
  {
    id: "contact",
    heading: "Contact",
    body: (
      <>
        <p>
          Questions about these terms, about a booking or about joining the
          network go through the <Link href="/contact">contact form</Link>.
          Choose the subject that fits and include the city, the hostel and your
          dates where a booking is involved.
        </p>
        <p>
          These terms will be updated as the service goes live, and the date at
          the top of this page shows when they last changed. The registered
          details of the company operating NEXT STOP, and the law and courts
          that govern these terms, will be stated here before booking opens
          rather than guessed at now.
        </p>
      </>
    ),
  },
];

export default function TermsPage() {
  return (
    <LegalPageLayout
      eyebrow="Legal"
      title="Terms &"
      accent="Conditions"
      subtitle="How the NEXT PASS works, who your booking is really with, and what each side of the network is responsible for."
      crumbLabel="Terms & Conditions"
      lastUpdated="20 September 2026"
      sections={sections}
    />
  );
}
